### ISSUE TITLE
Construct a basic network based on the description from Tucker's model description

### ISSUE THREAD

**Issue by billlyzhaoyh** [AIforGoodSimulator/network-model-python#1]
- People who live together are all connected to one another 
- People have a few random edges point to the neighbourhood (who are either friends or who live fairly close by that contact is not possible to avoid)
- People have a few random edges to the wider population (people they get in contact because the one big central food queue for example)

**Comment by thefirebanks** [comment]
Ok! Extracting from the Tucker model, we have: 

- 18,700 people total
- Isoboxes are prefabricated housing units with a mean occupancy of 10 individuals. 8100 individuals occupy isoboxes.
- Tents have a mean occupancy of 4 individuals. 10,600 individuals occupy tents. 
- The exact occupancy of each isobox or tent is drawn from a Poisson distribution, and individuals are assigned to isoboxes or tents randomly without regard to sex or age.
- 144 bathrooms, 1 food line

**Comment by billlyzhaoyh** [comment]
Yes! Those are the parameters he used for the ABM and quite a few stats there are heuristic assumptions like drawing people from Poisson distributions. We can infer the social network of that. Another information we do have is that he split people into 8 different ethnic groups and based on a study I read - people are much more likely to form a relationship with people of the same gender and same ethnicity so those gender data can also be utilised here.

**Comment by thefirebanks** [comment]
Lovely, we will extrapolate the gender/age ratio from the data you sent us on slack - but do you have population rates by ethnicity?

**Comment by billlyzhaoyh** [comment]
No, but we can take the assumptions Tucker made which he says is close to the arrival records so equal split into 8 ethnicities

**Comment by thefirebanks** [comment]
Marcelo and I just finished writing the code network that Tucker thought of! it can be used to create distinct networks for the isobox zone and the tents zones, should be fairly simple to connect them as well!
